SMU-likelion-smunion/SMUNION-frontend

css/components/navbar.css
css/pages/mypage-alert.css
css/pages/mypage.css
html/pages/mypage-alert.html
html/pages/mypage.html
js/mypage.js

feat : 마이페이지

---

css/pages/sign-up.css
html/pages/sign-up.html
js/pages/login.js
js/pages/sign-up.js

- 회원가입 유효성 검증
- 이메일 : @sangmyung.kr 사용
- 비밀번호는 8자 이상, 숫자와 특수문자를 포함
- 이메일로 인증코드 발송 / 확인 구현

feat : 로그인 / 로그아웃 / 회원가입 api 연결 완료

---

js/pages/notice-all.js

fix: 공지사항 필터링 오류 수정

---

css/pages/mypage-alert.css
css/pages/mypage.css
html/pages/mypage.html
js/pages/mypage.js

feat : 마이페이지 디자인 변경사항 적용

---

css/components/calendar.css
css/pages/club-full-calendar.css
css/pages/club-main.css
css/pages/club-notice-create.css
css/pages/home.css
html/pages/club-full-calendar.html
html/pages/club-main.html
html/pages/club-notice-create.html
html/pages/home.html
js/pages/club-main.js
js/pages/club-notice-create.js
js/pages/home.js

feat: 모든 화면 디자인 & js 수정

---

css/components/calendar.css
css/pages/club-full-calendar.css
css/pages/club-main.css
html/pages/club-full-calendar.html
html/pages/club-main.html
js/pages/club-main.js
js/pages/home.js

club-main
- 갤러리 가져오기
- 동아리 캘린더 안의 날짜별 공지 가져오기

feat: club-main 갤러리 & 캘린더 수정

---

js/pages/club-notice-create-attend.js
js/pages/club-notice-create-pay.js
js/pages/club-notice-create-vote.js
js/pages/club-notice-create.js

- memberId:1로 강제 설정후 공지사항 작성 테스트 -> 추후 동아리 선택 기능 완료되면 수정 예정

feat: 공지 데이터 구성 및 로컬 스토리지 저장 기능 추가

---

css/pages/mypage-alert.css
html/pages/mypage.html
js/pages/login.js
js/pages/mypage.js

- 동아리 프로필 변경 -> 동아리 리스트 모달
- 모달에서 선택된 동아리에 따른 마이페이지 프로필 변경
- 동아리 탈퇴 요청 구현

feat : 마이페이지 -> 동아리별 프로필 변경

---

css/components/calendar.css
html/pages/club-main.html
js/pages/club-full-calendar.js
js/pages/club-main.js
js/pages/home.js

- 캘린더 내부 공지 가져오기
- 캘린더 아래 공지 가져오기
- 오늘 날짜 공지 > dateDiv 클릭 시에만 상세공지로 이동하는 문제 수정 필요

feat: club-full-calendar 공지

---

js/pages/club-notice-create.js

feat: club-notice-create 완료 버튼 기능 수정

---

css/pages/club-full-calendar.css
html/pages/club-full-calendar.html
js/pages/club-full-calendar.js

- 동아리 이미지 클릭 시 모달창 표출
- 모달창의 동아리 클릭 시 해당 동아리 화면으로 전환

feat: club-full-calendar 헤더 기능 구현

---

html/pages/home.html
js/pages/club-main.js
js/pages/home.js

Reverts SMU-likelion-smunion/SMUNION-frontend#54

Revert "feat: home 캘린더 내부 공지 구현 & 전체 코드 리팩터링"

---

js/pages/home.js

feat: selected-date 수정

---

js/pages/club-full-calendar.js
js/pages/club-main.js
js/pages/club-notice-create.js
js/pages/home.js

- club-main / club-full-calendar
- 캘린더 아래 공지 클릭 > 상세 공지 페이지로 이동
- club-notice-create
- 공지 생성 조건 확인 코드에 return 추가
- home
- 경로 수정

feat: 상세공지 이동 적용

---

html/pages/club-main.html
html/pages/gallery-view-more.html
js/pages/club-main.js

- gallery-view-more 생성
- club-main '더보기'에 연결

feat: 갤러리 더보기 페이지 파일 생성

---

css/pages/gallery-view-more.css
html/pages/gallery-view-more.html
js/pages/club-full-calendar.js
js/pages/club-main.js
js/pages/club-notice-create.js
js/pages/gallery-create.js
js/pages/gallery-view-more.js
js/pages/gallery.js
js/pages/home.js

fix: 코드 수정

---

css/pages/gallery-edit.css
css/pages/gallery-view-more.css
html/pages/gallery-edit.html
js/pages/gallery-edit.js
js/pages/gallery-view-more.js
js/pages/home.js

feat: gallery 삭제 기능 구현

---

css/pages/gallery-create.css
css/pages/gallery-edit.css
css/pages/gallery.css
js/pages/gallery-create.js
js/pages/gallery-view-more.js

feat: 오류 수정

---

html/pages/club-main.html
html/pages/myClub.html
js/pages/myClub.js

- myClub에서 선택한 동아리에 대해 해당 동아리의 club-main 페이지로 이동
- 네비바 수정

feat: myClub > club-main 연결 구현

---

js/pages/club-main.js

- 필요에 따라 갤러리 관련 기능 중 운영진 권한 부분 수정 가능

feat: 운영진 여부 확인 코드

---

js/pages/club-main.js
js/pages/gallery-view-more.js

fix: 운영진 권한 기능 수정

---

css/pages/gallery-create.css
js/pages/gallery-create.js
js/pages/gallery-edit.js

gallery-create > 이미지 div css
gallery-edit > 갤러리 목록 순서 reverse

fix: 갤러리 사진 css & 갤러리 목록 순서 수정

---

html/pages/mypage.html
js/pages/mypage.js

동아리 탈퇴 요청 api 성공 -> 별도의 승인 없이 탈퇴 요청 승인 api 연결

fix: 동아리 탈퇴 요청 시, 바로 동아리 탈퇴 요청 승인
